### ISSUE TITLE
Overflowerror  Int too big to convert

### ISSUE THREAD

**Issue by rizalsyarif** [shamhi/YesCoinBot#22]
![image](https://github.com/shamhi/YesCoinBot/assets/54320055/ef2d426b-fbc1-4234-b648-620cbb3a055a)

**Comment by rizalsyarif** [comment]
my setting just like this, please help me sir 
![image](https://github.com/shamhi/YesCoinBot/assets/54320055/9654b070-3fcc-40ea-b74f-edc21d0905a5)

**Comment by shamhi** [comment]
python version ?

**Comment by rizalsyarif** [comment]
> python version ?

3.12 sir

**Comment by rizalsyarif** [comment]
my value on random taps is right ?

**Comment by shamhi** [comment]
you need 3.11 or 3.10

**Comment by rizalsyarif** [comment]
i used 3.10 and the problem not gone
