### ISSUE TITLE
Do not used with proxy

### ISSUE THREAD

**Issue by kamkuakuay** [shamhi/YesCoinBot#34]
![Screenshot_3](https://github.com/shamhi/YesCoinBot/assets/30189891/7c2ecd9b-6086-4fc2-b482-cea2d8e645c2)

**Comment by mikhailmid** [comment]
@kamkuakuay 
1. Your proxies not working
2. You have showed your login/pass to proxy


For the future proxy format is like:
http://ip:port@username:password
